package com.example.util;

public enum Step {
    MAIN,
    HELPCOMMAND,
    ORDERCOMMAND,
    CONTACTCOMMAND,
    LOCATIONCOMMAND,
    CREATIVETEAMCOMMAND,
    ORDERHOUSE,
    DISCOUNTHOUSE,
    PHOTOANDVIDEOHOUSE,
    RULESHOUSE,
    CONTACTHOUSE,
    LOCATIONHOUSE,
    FEATUREBOTCOMMAND,
    BOTINSTRUCTION, BOTINSTRUCTIONCOMMAND, PHONE, SMSCODE, GETFULLNAME, MYORDERS, NONE

}
